In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from matplotlib.colors import ListedColormap

In [2]:
dataset = pd.read_csv('./medinsur-1.csv')
dataset.head()

   age     sex     bmi  children  smoker     region    charges
0   19  female  27.900         0       1  southwest  16884.920
1   18    male  33.770         1       0  southeast   1725.552
2   28    male  33.000         3       0  southeast   4449.462
3   33    male  22.705         0       0   0rthwest  21984.470
4   32    male  28.880         0       0   0rthwest   3866.855

In [3]:
dataset.shape

(1338, 7)

In [4]:
mmf = dataset.loc[dataset['sex'] == 'male']
mmf

      age   sex     bmi  children  smoker     region    charges
1      18  male  33.770         1       0  southeast   1725.552
2      28  male  33.000         3       0  southeast   4449.462
3      33  male  22.705         0       0   0rthwest  21984.470
4      32  male  28.880         0       0   0rthwest   3866.855
8      37  male  29.830         2       0   0rtheast   6406.411
...   ...   ...     ...       ...     ...        ...        ...
1324   31  male  25.935         1       0   0rthwest   4239.893
1325   61  male  33.535         0       0   0rtheast  13143.340
1327   51  male  30.030         1       0  southeast   9377.905
1329   52  male  38.600         2       0  southwest  10325.210
1333   50  male  30.970         3       0   0rthwest  10600.550

[676 rows x 7 columns]

In [5]:
fmf = dataset.loc[dataset['sex'] == 'female']
fmf

      age     sex    bmi  children  smoker     region    charges
0      19  female  27.90         0       1  southwest  16884.920
5      31  female  25.74         0       0  southeast   3756.622
6      46  female  33.44         1       0  southeast   8240.590
7      37  female  27.74         3       0   0rthwest   7281.506
9      60  female  25.84         0       0   0rthwest  28923.140
...   ...     ...    ...       ...     ...        ...        ...
1332   52  female  44.70         3       0  southwest  11411.690
1334   18  female  31.92         0       0   0rtheast   2205.981
1335   18  female  36.85         0       0  southeast   1629.834
1336   21  female  25.80         0       0  southwest   2007.945
1337   61  female  29.07         0       1   0rthwest  29141.360

[662 rows x 7 columns]

In [6]:
mmf = mmf.dropna()
fmf = fmf.dropna()

In [7]:
X1 = fmf.iloc[:, [0, 2, 3]].values
y1 = fmf.iloc[:, [4]].values

fmf.head()

   age     sex    bmi  children  smoker     region    charges
0   19  female  27.90         0       1  southwest  16884.920
5   31  female  25.74         0       0  southeast   3756.622
6   46  female  33.44         1       0  southeast   8240.590
7   37  female  27.74         3       0   0rthwest   7281.506
9   60  female  25.84         0       0   0rthwest  28923.140

In [8]:
X2 = mmf.iloc[:, [0, 2, 3]].values
y2 = mmf.iloc[:, [4]].values

mmf.head()

   age   sex     bmi  children  smoker     region    charges
1   18  male  33.770         1       0  southeast   1725.552
2   28  male  33.000         3       0  southeast   4449.462
3   33  male  22.705         0       0   0rthwest  21984.470
4   32  male  28.880         0       0   0rthwest   3866.855
8   37  male  29.830         2       0   0rtheast   6406.411

In [9]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1
                                                   , y1
                                                   , test_size=0.25
                                                   , random_state=1)

In [10]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2
                                                   , y2
                                                   , test_size=0.25
                                                   , random_state=1)

In [11]:
sc1 = StandardScaler()
X1_train = sc1.fit_transform(X1_train)
X1_test = sc1.transform(X1_test)
sc2 = StandardScaler()
X2_train = sc2.fit_transform(X2_train)
X2_test = sc2.transform(X2_test)

In [12]:
fem = LogisticRegression()
fem.fit(X1_train, y1_train)

C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [13]:
mal = LogisticRegression()
mal.fit(X2_train, y2_train)

C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [14]:
y1_pred = fem.predict(X1_test)
print(np.concatenate((y1_pred.reshape(len(y1_pred),1)
                                    , y1_test.reshape(len(y1_test), 1))
                                                    , 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

In [15]:
y2_pred = mal.predict(X2_test)
print(np.concatenate((y2_pred.reshape(len(y2_pred),1)
                                    , y2_test.reshape(len(y2_test), 1))
                                                    , 1))

[[0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]

In [16]:
cm1 = confusion_matrix(y1_test, y1_pred)
print(cm1)

accuracy_score(y1_test, y1_pred)

[[133   0]
 [ 33   0]]

0.8012048192771084

In [17]:
cm2 = confusion_matrix(y2_test, y2_pred)
print(cm2)

accuracy_score(y2_test, y2_pred)

[[138   0]
 [ 31   0]]

0.8165680473372781

In [18]:
def calculate_bmi(weight, height):
    height_in_meters = height / 100  # Convert height from cm to meters
    bmi = weight / (height_in_meters ** 2)
    return bmi

In [ ]:
# name = input("Enter the value for Name: ")
# age = int(input("Enter the value for Age: "))
# sex = input("Enter the value for Sex: ")
# weight = float(input("Enter the value for Weight: "))
# height = float(input("Enter the value for Height: "))
# child = int(input("Enter the value for Number of Children: "))
# bmi = calculate_bmi(weight, height)
# user_input = np.array([[age, bmi, child]])

In [ ]:
# validation for gender

# if sex == 'M':
#     prediction = mal.predict_proba(user_input)
#     print("Probability of being a smoker: ")
#     print(prediction[0,1])
#     smk = mmf.loc[mmf['smoker'] == '1']
#     nsmk = mmf.loc[mmf['smoker'] == '0']
#     smkx = mmf.iloc[:, [0, 2, 3]].values
#     smky = mmf.iloc[:, [-1]].values
#     nsmkx = mmf.iloc[:, [0, 2, 3]].values
#     nsmky = mmf.iloc[:, [-1]].values
    
# elif sex == 'F':
#     prediction = fem.predict_proba(user_input)
#     print("Probability of being a smoker: ")
#     print(prediction[0,1])
#     smk = fmf.loc[fmf['smoker'] == '1']
#     nsmk = fmf.loc[fmf['smoker'] == '0']
#     smkx = fmf.iloc[:, [0, 2, 3]].values
#     smky = fmf.iloc[:, [-1]].values
#     nsmkx = fmf.iloc[:, [0, 2, 3]].values
#     nsmky = fmf.iloc[:, [-1]].values

In [ ]:
#reuse these 
smokermod = LinearRegression().fit(smkx, smky)
nsmokermod =  LinearRegression().fit(nsmkx, nsmky)

smokermod.intercept = smokermod.intercept_
smokermod.coef = smokermod.coef_

nsmokermod.intercept = nsmokermod.intercept_
nsmokermod.coef = nsmokermod.coef_

# declared variables are the ff:
# intercept, coefficients, model
# UI has separate user_input

def charges(intercept, coefficients, model, user_input):        
    charge = model.predict(user_input)
    np.round(charge, 2)
    print("Charges: ", charge)
    
isSmoker = True
if (prediction[0,1] >= 0.75):
    isSmoker = True
elif (prediction[0,1] <= 0.25):
    isSmoker = False
if isSmoker is True:
    charges(smokermod.intercept, smokermod.coef, smokermod, user_input)
elif isSmoker is False:
    charges(nsmokermod.intercept, nsmokermod.coef, nsmokermod, user_input)

In [ ]:
from tkinter import *
from tkinter import messagebox


mainFrame = Tk()
mainFrame.title("Medical Insurance Computer")
mainFrame.geometry('500x400')

# Create Frames
frameFirst = Frame(mainFrame)
frameFirst.grid(row=0, column=0)
frameSecond = Frame(mainFrame)
frameSecond.grid(row=0, column=1)
frameThird = Frame(mainFrame)
frameThird.grid(row=0, column=2)

# Set Values (Assuming dataset is defined)
age_min = 18
age_max = 65

bmi_min = 18.5
bmi_max = 24.9

children_min = 0
children_max = 5

# Drop Down Gender
chooseGender = [
    "Male",
    "Female"
]

# DataType of Gender Text
clickedGender = StringVar()
clickedGender.set("Male")

# DataType of Name Text
clickedName = StringVar()
clickedName.set("")

# DataType of Age Text
clickedAge = StringVar()
clickedAge.set("")

# DataType of Weight Text
clickedWeight = StringVar()
clickedWeight.set("")

# DataType of Height Text
clickedHeight = StringVar()
clickedHeight.set("")

# DataType of Children Text
clickedChildren = StringVar()
clickedChildren.set("")

# Visible UI
# Input Areas
# Show Name Input Area
labelName = Label(frameFirst, text="Name")
labelName.grid(row=0, column=0, padx=5, pady=5)
entryName = Entry(frameFirst, textvariable=clickedName)
entryName.grid(row=0, column=1, padx=5, pady=5)

# Show Dropdown Gender Menu
labelGender = Label(frameFirst, text="Gender")
labelGender.grid(row=1, column=0, padx=5, pady=5)
dropGender = OptionMenu(frameFirst, clickedGender, *chooseGender)
dropGender.grid(row=1, column=1, padx=5, pady=5)

# Show Age Input Area
labelAge = Label(frameFirst, text="Age")
labelAge.grid(row=2, column=0, padx=5, pady=5)
entryAge = Entry(frameFirst, textvariable=clickedAge)
entryAge.grid(row=2, column=1, padx=5, pady=5)

# Show Weight Input Area
labelWeight = Label(frameFirst, text="Weight")
labelWeight.grid(row=3, column=0, padx=5, pady=5)
entryWeight = Entry(frameFirst, textvariable=clickedWeight)
entryWeight.grid(row=3, column=1, padx=5, pady=5)

# Show Height Input Area
labelHeight = Label(frameFirst, text="Height")
labelHeight.grid(row=4, column=0, padx=5, pady=5)
entryHeight = Entry(frameFirst, textvariable=clickedHeight)
entryHeight.grid(row=4, column=1, padx=5, pady=5)

# Show Children Input Area
labelChildren = Label(frameFirst, text="Children")
labelChildren.grid(row=5, column=0, padx=5, pady=5)
entryChildren = Entry(frameFirst, textvariable=clickedChildren)
entryChildren.grid(row=5, column=1, padx=5, pady=5)

def show_Results():
    # Output Areas
    # Show Name Output Area
    labelName = Label(frameSecond, text="Name")
    labelName.grid(row=0, column=0, padx=5, pady=5)
    OutputName = Label(frameSecond, text=clickedName.get())
    OutputName.grid(row=0, column=1, padx=5, pady=5)

    # Show Gender Output Menu
    labelGender = Label(frameSecond, text="Gender")
    labelGender.grid(row=1, column=0, padx=5, pady=5)
    OutputGender = Label(frameSecond, text=clickedGender.get())
    OutputGender.grid(row=1, column=1, padx=5, pady=5)

    # Show Age Output Area
    labelAge = Label(frameSecond, text="Age")
    labelAge.grid(row=2, column=0, padx=5, pady=5)
    OutputAge = Label(frameSecond, text=clickedAge.get())
    OutputAge.grid(row=2, column=1, padx=5, pady=5)

    # Show Weight Output Area
    labelWeight = Label(frameSecond, text="Weight(kg)")
    labelWeight.grid(row=3, column=0, padx=5, pady=5)
    OutputWeight = Label(frameSecond, text=clickedWeight.get())
    OutputWeight.grid(row=3, column=1, padx=5, pady=5)

    # Show Height Output Area
    labelHeight = Label(frameSecond, text="Height(cm)")
    labelHeight.grid(row=4, column=0, padx=5, pady=5)
    OutputHeight = Label(frameSecond, text=clickedHeight.get())
    OutputHeight.grid(row=4, column=1, padx=5, pady=5)

    # Show BMI Output Area
    labelBMI = Label(frameSecond, text="BMI")
    labelBMI.grid(row=5, column=0, padx=5, pady=5)
    OutputBMI = Label(frameSecond, text=calculate_bmi(clickedWeight.get(), clickedHeight.get()))
    OutputBMI.grid(row=5, column=1, padx=5, pady=5)

    # Show Children Output Area
    labelChildren = Label(frameSecond, text="Children")
    labelChildren.grid(row=6, column=0, padx=5, pady=5)
    OutputChildren = Label(frameSecond, text=clickedChildren.get())
    OutputChildren.grid(row=6, column=1, padx=5, pady=5)

    # Show Fee Output Area
    user_input = np.array([[float(clickedAge.get()), calculate_bmi(clickedWeight.get(), clickedHeight.get()), float(clickedChildren.get())]])
    labelFee = Label(frameThird, text="Fee")
    labelFee.grid(row=0, column=0, padx=5, pady=5)
    OutputFee = Label(frameThird, text=charges(nsmokermod.intercept, nsmokermod.coef, nsmokermod, user_input))
    OutputFee.grid(row=0, column=1, padx=5, pady=5)

# Calculations
def calculate_bmi(weight, height):
    try:
        weight = float(weight)
        height = float(height)
        height_in_meters = height / 100  # Convert height from cm to meters
        bmi = weight / (height_in_meters ** 2)
        bmi = round(bmi, 2)
        return bmi
    except ValueError:
        return "Invalid input"

# Display Results Button
btn_GetResults = Button(frameFirst, text='Calculate', command=validate_input)
btn_GetResults.grid(row=6, column=0, padx=5, pady=5)

# Value Validation
def validate_input():
    validation_errors = []

    # Validate Age
    try:
        age = float(clickedAge.get())
        if age < age_min or age > age_max:
            validation_errors.append("Age must be between {} and {}.".format(age_min, age_max))
    except ValueError:
        validation_errors.append("Invalid age input.")

    # Validate Weight
    try:
        weight = float(clickedWeight.get())
        if weight <= 2 or weight >= 635:
            validation_errors.append("Weight must be from 2 to 635 kg.")
    except ValueError:
        validation_errors.append("Invalid weight input.")

    # Validate Height
    try:
        height = float(clickedHeight.get())
        if height < 55 or height > 272:
            validation_errors.append("Height must be from 55 to 272 cm.")
    except ValueError:
        validation_errors.append("Invalid height input.")

    # Validate Children
    try:
        children = int(clickedChildren.get())
        if children < children_min or children > children_max:
            validation_errors.append("Number of children must be between {} and {}.".format(children_min, children_max))
    except ValueError:
        validation_errors.append("Invalid children input.")

    if validation_errors:
        show_error_messages(validation_errors)
    else:
        show_Results()

def show_error_messages(errors):
    error_message = "\n".join(errors)
    messagebox.showerror("Validation Error", error_message)

mainFrame.mainloop()